### ISSUE TITLE
problems on ubuntu 14.04

### ISSUE THREAD

**Issue by valruggero** [ponchoblesa/GoPro-Studio-for-linux#1]
Hi ponchoblesa,
thanks for GoPro-Studio-for-linux!
Unfortunately the script gopro_import.sh does not work on ubuntu 14.04.
Running the script nothing happens. Only the folder GoPro is created, but it is empty.
Adding '-x' to the first line I read some output on the terminal. The script stopped on this point:
- local folder_match=/media/gp/102GOPRO/G0237343.JPG
- '[' -d //media/gp/102GOPRO/G0237343.JPG ']'
- first_level=("${FOLDERS_LIST_RETURN[@]}")

Thanks in advance!
Ruggero

**Comment by ponchoblesa** [comment]
Hi Ruggero,

Thanks for reporting, this is the first feedback that I have of these scripts. Apparently for what you are telling me, I guess that your camera folder is wrong set.

For your particular case, I guess that your camera folder is "/media/gp"

```
   #!/bin/bash

   CAMERA_DIR="/media/gp"
   ...
```

The "CAMERA_DIR" variable should point to the root folder of the memory card. Make this check for me and tell me if works. Otherwise, tell me please your variables setup and if you are running the script with the memory card in a stick or card reader, or if you are running it trying to access to the plugged GoPro.

Thank you!

Poncho

**Comment by ponchoblesa** [comment]
Hi Ruggero,

Any new on this? Can I close the issue?

Cheers

Poncho

**Comment by valruggero** [comment]
Hi Poncho,
On my notebook with ubuntu 14.04 I have these problems, but on
my workstation (also with ubuntu 14.04) all works fine!

So the problem is on my notebook configuration, sorry.

I need more "free time" to investigate.
You can close the issue.

Cheers
Ruggero

On 31 January 2016 at 18:49, ponchoblesa notifications@github.com wrote:

> Hi Ruggero,
> 
> Any new on this? Can I close the issue?
> 
> Cheers
> 
> Poncho
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ponchoblesa/GoPro-Studio-for-linux/issues/1#issuecomment-177563631
> .

## 

/****************************************
       /\          Ruggero Valentinotti
      //\  /\
     ///\\//\    Frazione Tozzaga
    ////\\/\\   Via alle Pozze, 6
   /////\\\\\  38022 CALDES (TN)
       ||////\\\ ITALY
  _____||**_||__**_
****************************************/
Io stimo più il trovar un vero, benché di cosa leggiera,
che 'l disputar lungamente delle massime questioni senza conseguir verità
nissuna
Galileo Galilei, 1609

**Comment by ponchoblesa** [comment]
Thank you Ruggero. Good luck with it ;-)
